import 'package:feather_icons/feather_icons.dart';
import 'package:flutter/material.dart';
import 'package:flutter_quill/flutter_quill.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:jurney_blog_app/core/constant/my_assets.dart';
import 'package:jurney_blog_app/core/constant/my_colors.dart';
import 'package:velocity_x/velocity_x.dart';
part '../add_post.dart';
part 'add_post_view_model.dart';
